import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class SwitchServiceService {
  constructor() {}

  switchList(): string[] {
    return [
      'the legend of zelda breath of the wild',
      "yoshi's crafted world",
      '51 worldwide games',
      'super smash bros ultimate',
      'dragonball fighter z',
      'streets of rage 4',
      'megaman 11',
      'balan woderworld',
      'kirby star allies',
      'kirby et le monde oublié',
      'megaman classic collection 1 + 2',
      'jumps force deluxe edition',
      'the survivalists',
      'yonder the cloud catcher chronicles',
      'prinny 1 + 2: exploded and reloaded',
      'fairy tails',
      "dragon's dogma dark ariser",
      'sword art online: hollow realization deluxe edition',
      'torment / icewind',
      'remothered',
      'captain tsubasa rise of new champions',
      'cytus',
      'disgaea 5 complete',
      'rayman legends',
      'astral chain',
      'final fantasy X/X2',
      'call of cthulhu',
      'finding teddy 2: definitive edition',
      'state of mind',
      'tales of vesperia: definitive edition',
      'deponia',
      'blazblue cross tag battle',
      'fire emblem three houses',
      'bloodstained',
      'trine: ultimate collection (1 à 4)',
      'octopath traveler',
      'south park: the fractured but whole',
      'mortal kombat 11',
      'carrion',
      'doom',
      'trial rising',
      'sonic mania',
      "assassin's creed 3 remastered",
      'AI: the somnium files',
      'ghostbusters the video game: remastered',
      'sayonara wild hearts',
      "assassin's creed: the rebel collection (black flag / rogue)",
      'diablo 3 eternal collection',
      'zombie army trilogy',
      'wwe 2k18',
      'moonlighter',
      'ultra street fighter 2 the final challengers',
      'piczle puzzle pack 3 in 1',
      'megaman X anniversary collection 2',
      'ringfit adventure',
      'dragon marked for death',
      'resident evil origins collection',
      'overcooked: special edition',
      'this is police 2',
      'skyrim',
      'mario party superstars',
      'ion fury',
      'stern pinball arcade',
      'civilization VI',
      'this war of mine: complete edition',
      'crosscode',
      'under night in-birth exe:late[cl-r]',
      'guilty gear 20th anniversary pack',
      'blade strangers',
      'bladearcus rebellion',
      'resident evil revelation: unveiled ediiton',
      'super mario party',
      'snipperclips plus: les deux font la pair',
      'titan quest',
      'darksiders: warmastered edition',
      "taiko no tatsujin drum'n'fun",
      'puyo puyo esports',
      'gris',
      'catherine: full body',
      'this is police',
      'Mario + The Lapins Cretins : Kingdom battle',
      "l'aventure layton: katrielle et la conspiration des milliardaires: edition deluxe",
      'starlink: battle for atlas',
      "luigi's mansion 3",
      'mariokart 8 deluxe',
      'mario & sonic aux jeux olympiques de tokyo 2020',
      'super mario 3d all stars',
      'mario strikers battle league football',
      'super mario maker 2',
      'senran kagura peach ball',
      "oddworld stranger's wrath HD",
      'Gunvolt Chronicles: Luminous Avenger iX',
      'oninaki',
      'Onimusha: Warlords',
      'animal crossing new horizons',
      'moving out',
      'ministry of broadcast',
      'overcooked 2',
      "black future '88",
      'children of morta',
      'okami',
      'the binding of isaac: afterbirth +',
      'darkest dungeon: ancestral edition',
      'dead cells',
      'the raven remastered',
      "baldur's gate 1 + 2",
      'Ace Attorney Trilogy',
      'Gal Metal',
      "the legend of zelda link's awakening",
      'warioware get it together !',
      "super mario 3d world + bowser's fury",
      'dragon quest XI: les combattans de la destinée S',
      'ni no kuni: la vengeance de la sorciere celeste',
      'Lethal League',
      'Azure Striker Gunvolt',
      'yesterday origins',
      'for the king',
      'northgard',
      'superbeat: xonic',
      'SNK Heroines: Tag Team Frenzy',
      'axiom verge',
      'victor vran: overkill edition',
      'paper mario: the origami king',
      'xenoblade chronicles 2',
      'lost sphear',
      'pocky & rocky reshrined',
      'puzzle bobble everybubble !ng start',
      'pokemon epee',
    ];
  }
}
