import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class Xbox360SearchService {
  constructor() {}
  xbox360List(): string[] {
    return [
      '50 cent blood on the sand',
      'alan wake',
      'alien vs predator',
      "assassin's creed",
      "assassin's creed 2",
      "assassin's creed brotherhood",
      "assassin's creed revelations",
      "asura's wrath",
      'banjo & kazooie nuts & bolts',
      'batman arkham origins',
      'battlefield 3',
      'battlefield bad company 2',
      'bayonetta',
      'binary domain',
      'bioshock',
      'bioshock 2',
      'bioshock infinite',
      'blazing angels squadrons of ww2',
      'bound by flame',
      'borderlands edition game of the year',
      'borderlands 2',
      "brother in arms hell's highway",
      'brutal legend',
      'burnout paradise',
      "cabela's survival",
      'call of duty 2',
      'call of duty 3',
      'call of duty black ops',
      'call of duty ghosts',
      'call of duty modern warfare 2',
      'call of duty modern warfare 3',
      'call of duty world at war',
      'call of juarez bound in blood',
      'call of juarez the cartel',
      'castlevania lord of shadow',
      'civilization revolution',
      'command and conquer 3 la fureur de kain',
      'conan',
      'condemned',
      'crackdown',
      'crysis 2',
      'crysis 3',
      'darkness',
      'darkness 2',
      'darksiders',
      'darksiders 2',
      'darkvoid',
      'dead or alive 3',
      'dead or alive 4',
      'dead space 2',
      'deus ex human revolution',
      'dirt 3',
      'dragon age 2',
      'dragon age origins',
      'dungeon siege 3',
      'duke nukem forever',
      'dynasty warriors: strikeforce',
      'eat lead',
      'enchanted arms',
      'enslaved',
      'fable 2',
      'fable 3',
      'fallout 3',
      'fallout new vegas',
      'far cry 2',
      'far cry 3',
      'fear files',
      'fear: first encounter assault recon',
      'fear 2: project origin',
      'fear 3',
      'fight night champion',
      'final fantasy XIII',
      'final fantasy XIII-2',
      'frontlines: fuel of war',
      'fuel',
      'justcause 2',
      'gears of war',
      'gears of war 2',
      'gears of war 3',
      'gears of war judgment',
      'grand theft auto 4',
      'grid 2',
      'halo 3',
      'halo 3 odst',
      'halo reach',
      'hitman absolution',
      'kamoe: elements of power',
      'kane & lynch 2: dog days',
      'le tour de france',
      'lost odyssey',
      'lost planet: extreme condition',
      'lost planet 2',
      'lost planet 3',
      'mafia 2',
      'mass effect',
      'mass effect 2',
      'mass effect 3',
      'max payne 3',
      'metalgear rising',
      'midnight club los angeles',
      'mortal kombat',
      'ninja gaiden 2',
      'oblivion',
      'onechanbara bikini samurai squad',
      'operation flashpoint red river',
      'overlord',
      'overlord 2',
      'perfect dark zero',
      'portal 2',
      'prey',
      'prince of persia',
      'rage',
      'rayman legends',
      "reckoning: les royaumes d'amalur",
      'red dead redemption',
      'red dead revolver',
      'red faction armageddon',
      'resident evil: operation racc cityoon',
      'risen',
      'risen 3',
      'ruse',
      'saints row',
      'saints row 2',
      'saints row: the third',
      'saints row 4',
      'skate 3',
      'sniper elite V2',
      'sos fantomes: le jeu video',
      'spec ops the line',
      'split second velocity',
      'ssx',
      'star ocean: the last hope',
      'star wars: le pouvoir de la force 2',
      'star wars: republic commando',
      'star wars: force unleashed',
      'street fighter 4',
      'supreme commander 2',
      'syndicate',
      'table tennis',
      'tekken 6',
      'the bureau: xcom declassified',
      'the witcher 2: assassins of kings / enhaiced edition',
      'timeshift',
      'timesplitters 2',
      'tomb raider underworld',
      "tom clancy's endwar",
      "tom clancy's hawk",
      "tom clancy's rainbow six vegas",
      "tom clancy's rainbow six vegas 2",
      "tom clancy's splinter cell",
      "tom clancy's splinter cell blacklist",
      "tom clancy's splinter cell chaos theory",
      "tom clancy's splinter cell conviction",
      "tom clancy's splinter cell double agent",
      "tom clancy's splinter cell pandora tomorrow",
      'tron evolution',
      'tropico 4',
      'unreal tournament',
      'vanquish',
      'viva pinata: pagaille au paradis',
      'viva pinata: party animals',
      'xcom enemy unknown',
      '007 legends',
      '007 quantum of solace',
      'afro samurai',
      "a la croisée des mondes: la boussole d'or",
      'alone in the dark',
      'alpha protocol',
      'arcana heart 3',
      'arcania gothic4',
      'armored core for answer',
      "assassin's creed 3",
      'ace combat: assault horizon',
      'avatar: the game',
      'ballers chosen one',
      'batman arkham asylum',
      'batman arkham city',
      'brijing 2008',
      'bionic commando',
      'blacksite',
      'blazeblue calamity trigger',
      'blitz the league',
      'blood bowl',
      'bodycount',
      'brink',
      'bulletstorm',
      'carnival bouge ton corps',
      'club',
      'condemned 2',
      'conflict: denied ops',
      'coupe du monde de la fifa: bresil 2014',
      'dance central',
      'dance central 2',
      'dance central 3',
      'dark messiah of might and magic',
      'dark sector',
      'dead island',
      'dead island riptide',
      'deadrising',
      'deadrising 2',
      'dead to rights retribution',
      'defiance',
      'def jam icon',
      'def jam rapstar',
      'devil may cry 4',
      'diablo 3',
      'dirt',
      'dirt 2',
      'dishonored',
      'divinity 2 ego dragonis',
      'dmc devil may cry',
      'dodonpachi resurrection: deluxe edition',
      'don king boxing',
      'dragonball rising blast 2',
      'dragonball z burstlimit',
      "dragon's dogma",
      'ea sports fight night round 3',
      'el shaddai',
      'enemy front',
      'eragon',
      'eternal sonata',
      'f1 2010',
      'f1 2011',
      'f1 2012',
      'facebreaker',
      'fifa 09',
      'fifa 11',
      'fifa 13',
      'fifa 14',
      'fifa street',
      "fist of the north star: ken's rage",
      "fist of the north star: ken's rage 2",
      'flatout ultimate carnage',
      'football manager 2006',
      'forza motorsport 4',
      'front mission evolved',
      'full auto',
      'fuse',
      'grand chelem tennis 2',
      'grand theft auto 5',
      'guitar hero 2',
      'guitar hero 3 legends of rock',
      'guitar hero warriors of rock',
      'guitar hero world tour',
      'gun',
      'history legends of war',
      'homefront',
      'hour of victory',
      "hunted the demon's forge",
      'ihf handball challenge 14',
      "infernal hell's vengeance",
      'inversion',
      "james cameron's avatar: the game",
      "clive barker's jericho",
      'jonah lomu rugby challenge',
      "pirates des caraibes jusqu'au bout du monde",
      'kane & lynch: dead men',
      'khights contract',
      'kinect adventures !',
      'l.a. noire',
      'la legende de beowulf: le jeu',
      'la memoire dans la peau',
      'legendary',
      'leisure suit larry box office bust',
      'le parrain 2',
      'les experts: crime scene investigation complots à las vegas',
      'le tour de france 2012',
      'le tour de france 2013 - 100th edition',
      'lost',
      "madagascar 3 bons baisers d'europe",
      'madden nfl 06',
      'madden nfl 13',
      'madden nfl 15',
      'magna carta 2',
      'marvel vs capcom 3 fate of two worlds',
      "marvel super hero squad: le gant de l'infini",
      'medal of honor',
      'medal of honor warfighter: limited edition',
      "mercenaries 2 l'enfer des favelas",
      'metro 2033',
      'metro last light',
      'mindjack',
      'motogp 07',
      'n3 ninety-nine nights',
      'ninety-nine nights 2',
      "nail'd",
      'narnia le prince caspian',
      'naruto: rise of a ninja',
      'naruto shippuden: ultimate ninja storm generations',
      'naruto shippuden: ultimate ninja storm 2',
      'naruto shippuden: ultimate ninja storm 3',
      'naruto: the broken bond',
      'nba 2K12',
      'nba street homecourt',
      'need for speed the run',
      'need for speed shift',
      'nhl 2k6',
      'nba 2k11',
      'nba 2k10',
      'nba 2k7',
      'nhl 07',
      'nhl 09',
      'ninja blade',
      'pro evolution soccer 2008',
      'pro evolution soccer 2009',
      'pro evolution soccer 2010',
      'pro evolution soccer 6',
      'pgr project gothamv racing 3',
      'project gotham racing 4',
      'prototype',
      'prototype 2',
      'quake 4',
      'quake wars enemy territory',
      'rabbids alive & kicking',
      'race pro',
      'rain vampire',
      'raven squad',
      'remember me',
      'resident evil 5 gold edition',
      'resident evil 6',
      'resident evil revelations',
      'the chronicles of riddick: assault on dark athena',
      'ride to hell retribution',
      'rise of the argonauts',
      'risen 3 titan lords: first edition',
      'rock band 3',
      'rocksmith 2014 edition',
      'rogue warrior',
      'le royaume de gahoole la legende des gardiens',
      'ridge racer unbounded',
      'rugby 15',
      'rugby world cup 2011',
      'sbk 08 superbike world championship',
      'sbk 09 superbike world championship',
      'sbk 2011 fim superbike world championship',
      'sbk x superbike world championship',
      'scene it ? box-office',
      'section 8',
      'sega rally',
      'sega superstars tennis',
      'shaun white skateboarding',
      'shaun white snowboarding',
      'shellshock 2 blood trails',
      'shift 2 unleashed',
      'singularity',
      'skyrim',
      'sleeping dogs',
      'smash court tennis 3',
      'smackdown vs raw 2008',
      'smackdown vs raw 2009',
      'smackdown vs raw 2011',
      'snipers',
      'sniper ghost warrior',
      'soldier of fortune payback',
      'soulcalibur 4',
      'spacemarine warhammer 40000',
      'star trek',
      'stoked big air edition',
      'stormrise',
      'stranglehold',
      'summer challengr: athletics tournament',
      'supremacy mma',
      'terminator renaissance',
      'the cursed crusade',
      'thief',
      'tiger woods pga tour 06',
      'tiger woods pga tour 08',
      'titanfall',
      'tna impact ! total nonstop action wrestling',
      'tomb raider',
      "tony hawk's project 8",
      "tony hawk's proving ground",
      'top spin 2',
      'top spin 3',
      'top spin 4',
      'transformers la guerre pour cybertron',
      'transformers the dark spark',
      'tropico 3',
      'truck racer',
      'turning point fall of liberty',
      'turok',
      'two worlds',
      'two worlds 2',
      'uefa euro 2008',
      'ufc 2009 undisputed',
      'ufc 2010 undisputed',
      'vancouver 2010',
      'velvet assassin',
      'viking: battle for asgard',
      'virtua tennis 2009',
      'virtua tennis 3',
      'virtua tennis 4',
      'W12',
      'W13',
      'W2k14',
      'w all stars',
      'wall e',
      'wanted les armes du destin',
      'warhammer battle march',
      'wartech senko no ronde',
      'watchmen la fin approche chapitre 1 et 2',
      'wet',
      'wheelman',
      'world of tanks: xbox 360 edition',
      'xboxlive arcade',
      'xboxlive arcade unplugged volume 1',
      'x-men origins wolverine',
      'wrc fia world rally championship 4',
      'morphx',
      'damnation',
      'the amazing spider-man',
      'alien isolation edition nostromo',
      'power rangers super samurai',
      'mx vs atv supercross',
      'motogp 09/10',
      'mxgp',
      'batman the telltale series',
      'devil may cry HD collection',
      'great battles medieval',
      'winter sports the great tournament 2010',
      'crime & punishments sherlock holmes',
      'shadowrun',
      'prison break',
      'red faction guerilla',
    ];
  }
}
