import { Injectable } from '@angular/core';
import { GameList } from '../game-list';

@Injectable({
  providedIn: 'root',
})
export class XboxSearchService implements GameList {
  constructor() {}
  xboxList(): string[] {
    return [
      '11-11 memories retold',
      'agony',
      "assassin's creed IV black flag",
      "assassin's creed odyssey",
      "assassin's creed origins",
      "assassin's creed valhalla",
      'a way out',
      'battlefield 1',
      'battlefield 4',
      'battlefield hardline',
      'bloodbowl 2',
      'borderland 3',
      'call of duty advanced warfare',
      'call of duty black ops 3',
      'call of duty black ops 4',
      'call of duty cold war',
      'call of duty infinite warfare',
      'call of duty vanguard',
      'call of duty ww2',
      'chorus',
      'control',
      'cyberpunk 2077',
      'deadrising 3',
      'deadrising 4',
      'devil may cry 5',
      'divinity 2',
      'dishonored 2',
      'dragonball xenoverse 2',
      'dragonball z: kakarot',
      'dying light',
      'dynasty warriors 8 empires',
      'extinction',
      'far cry 4',
      'far cry 5',
      'far cry 6',
      'far cry primal',
      'final fantasy xv',
      'forza 5',
      'has been heroes',
      'hogwarts legacy',
      'homefront the revolution',
      'immortal fenyx rising',
      'it take two',
      'jedi fallen order',
      'judgment',
      'kingdomcome delivrance',
      'mafia 3',
      'marvel avengers',
      'monster hunter world',
      'murdered',
      'nba2k14',
      'nba2k15',
      'nba2k16',
      'nba2k17',
      'one piece burning blood',
      'prey xboxone',
      'resident evil 2 remake',
      'rise of the tomb raider',
      'ryse son of rome',
      'sekiro',
      'shadow of the tomb raider',
      'shapeup',
      'shenmue 1 & 2',
      'sniper 3',
      'soul calibur 4',
      "south park l'annale du destin",
      'styx',
      'technomancer',
      'the crew',
      'titanfall',
      'tomb raider definitive edition',
      "tom clancy's rainbow six siege",
      'valkiria chronicles 4',
      'vampyr',
      'watch dogs',
      'watch dogs 2',
      'watch dogs legion',
      'warhammer 40,000 inquisitor martyr',
      // 'warhammer vermintide 2',
      'warhammer the end times vermintide ',
      'wolfenstein the new order',
      'yakuza like a dragon',
      'yesterday origins',
      'zombie army trilogy',
      'zoo tycoon',
      'Gotham Knights: special edition',
      'arslan the warriors of legend',
      'railway empire',
      'bladestorm nightmare',
      'gears of war 4',
      'the surge 2',
      'ride 2',
      'rugby challenge 3',
      'gears 5',
      'marvel midnight suns',
      'crackdown 3',
    ];
  }
  getList(): string[] {
    return this.xboxList();
  }
}
